# Generated by Django 4.0.5 on 2022-08-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_surname', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_dni', models.CharField(blank=True, db_column='customer_DNI', max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_id', models.IntegerField()),
                ('tipo_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movimiento', models.IntegerField(blank=True, db_column='id movimiento', null=True, unique=True)),
                ('numero_de_cuenta', models.IntegerField(blank=True, db_column='numero de cuenta', null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('tipo_de_operacion', models.IntegerField(blank=True, db_column='tipo de operacion', null=True)),
                ('hora', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
    ]
