# Generated by Django 4.0.5 on 2022-08-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_alter_tarjeta_cvv_alter_tarjeta_marca_tarjeta_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_cliente',
            field=models.CharField(default='apellido_cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni_cliente',
            field=models.CharField(default='dni_cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(default='nombre_cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarjetas.tarjeta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(default='tipo_cliente', max_length=255),
        ),
    ]
