# Generated by Django 4.0.5 on 2022-08-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('movimiento_id', models.IntegerField(default='movimiento_id', primary_key=True, serialize=False)),
                ('numero_cuenta', models.IntegerField(default='numero_cuenta')),
                ('monto', models.IntegerField(default='monto')),
                ('tipo_operacion', models.CharField(default='tipo_operacion', max_length=50)),
                ('hora', models.TimeField()),
            ],
        ),
    ]
