# Generated by Django 4.0.5 on 2022-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('movimiento_id', models.IntegerField(default='movimiento_id', primary_key=True, serialize=False)),
                ('numero_cuenta', models.IntegerField(default='numero_cuenta')),
                ('monto', models.IntegerField(default='monto')),
                ('tipo_operacion', models.CharField(default='tipo_operacion', max_length=50)),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='balance',
            field=models.IntegerField(default='balance'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cliente_id',
            field=models.IntegerField(default='cliente_id'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta_id',
            field=models.IntegerField(default='cuenta_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(default='tipo_cuenta', max_length=50),
        ),
    ]
