# Generated by Django 4.1 on 2022-08-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('cvv', models.IntegerField(max_length=3)),
                ('fecha_otorgamiento', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('tipo_tarjeta', models.CharField(max_length=10)),
                ('marca_tarjeta', models.CharField(max_length=50)),
            ],
        ),
    ]
