# Generated by Django 4.0.5 on 2022-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='cvv',
            field=models.IntegerField(default='cvv'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='marca_tarjeta',
            field=models.CharField(default='marca_tarjeta', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.IntegerField(default='numero', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo_tarjeta',
            field=models.CharField(default='tipo_tarjeta', max_length=10),
        ),
    ]
