# Generated by Django 4.1 on 2022-08-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('passw', models.CharField(max_length=16)),
                ('dni', models.IntegerField(max_length=50)),
            ],
        ),
    ]
