# Generated by Django 4.0.5 on 2022-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(default='dni'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='passw',
            field=models.CharField(default='password', max_length=16),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='usuario', max_length=12),
        ),
    ]
