# Generated by Django 4.0.5 on 2022-08-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_apellido_remove_cliente_dni_and_more'),
        ('login', '0003_alter_usuario_dni_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cliente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
