# Generated by Django 4.0.5 on 2022-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_date', models.DateField()),
                ('loan_total', models.IntegerField()),
                ('loan_type', models.CharField(max_length=50)),
            ],
        ),
    ]
