# Generated by Django 4.0.5 on 2022-08-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_apellido_remove_cliente_dni_and_more'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cliente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_date',
            field=models.DateField(default='loan_date'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_id',
            field=models.IntegerField(default='loan_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_total',
            field=models.IntegerField(default='loan_total'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_type',
            field=models.CharField(default='loan_type', max_length=50),
        ),
    ]
